SELECT NAME AS CUSTOMERS FROM CUSTOMERS
LEFT JOIN ORDERS AS O
ON CUSTOMERS.ID = O.CUSTOMERID AND O.ID IS NULL
WHERE O.ID IS NULL


SELECT CUSTOMERS.NAME AS `Customers`
FROM CUSTOMERS
WHERE CUSTOMERS.ID NOT IN (SELECT CUSTOMERID FROM ORDERS)