SELECT DEPARTMENT.NAME AS `DEPARTMENT`, E.NAME AS `EMPLOYEE`, E.SALARY
FROM EMPLOYEE AS E
INNER JOIN
    (SELECT DEPARTMENTID, MAX(SALARY) AS SALARY
    FROM EMPLOYEE
    GROUP BY DEPARTMENTID) T
ON T.SALARY = E.SALARY AND T.DEPARTMENTID = E.DEPARTMENTID
INNER JOIN
    DEPARTMENT
ON DEPARTMENT.ID = E.DEPARTMENTID